### ISSUE TITLE
Container should exit when vamp-workflow-agent finished execution

### ISSUE THREAD

**Issue by dragoslav** [magneticio/vamp-workflow-agent#17]
For instance this workflow should be executed every 5 seconds (PT5S, Chronos), and vamp-workflow-agent runs only once (VAMP_WORKFLOW_EXECUTION_PERIOD:  0)
```yaml
---
name    : allocation
breed   : allocation
schedule: 
  time:
    period: PT5S
environment_variables:
  VAMP_WORKFLOW_EXECUTION_PERIOD:  0
  VAMP_WORKFLOW_EXECUTION_TIMEOUT: 4
```

What happens is that vamp-workflow-agent is done but container is still running, thus Chronos will not schedule it again.
