### ISSUE TITLE
Wrong VAMP_URL set by default

### ISSUE THREAD

**Issue by iamtew** [magneticio/vamp-workflow-agent#8]
DC/OS 1.8.7

```text
Hi, I'm Vamp! How are you?

RUNNING SINCE     20-12-2016 08:27:58
VERSION           0.9.1-42-gbbc771e
UI VERSION        0.9.1-19-g8419161
PERSISTENCE       elasticsearch
PULSE             elasticsearch
KEY VALUE STORE   zookeeper
GATEWAY DRIVER    haproxy 1.6.x
CONTAINER DRIVER  marathon
WORKFLOW DRIVER   marathon
```

Workflow agent's are created by default, but the VAMP_URL variable is set incorrect, even if specified up Vamp when creating marathon app.

Default settings on a workflow:
```yaml
name: health
kind: workflow
breed:
  reference: health
status: running
schedule: daemon
environment_variables:
  VAMP_WORKFLOW_EXECUTION_TIMEOUT: '7'
  VAMP_KEY_VALUE_STORE_CONNECTION: zk-1.zk:2181
  VAMP_KEY_VALUE_STORE_PATH: /vamp/workflows/health
  VAMP_WORKFLOW_EXECUTION_PERIOD: '5'
  VAMP_KEY_VALUE_STORE_TYPE: zookeeper
  VAMP_URL: http://vamp-vamp.marathon.mesos:8080
scale:
  cpu: 0.1
  memory: 128.00MB
  instances: 1
network: HOST
arguments: []
```

Vamp marathon.json
```json
{
  "id": "vamp/vamp",
  "instances": 1,
  "cpus": 0.5,
  "mem": 1024,
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "magneticio/vamp:katana-dcos",
      "network": "BRIDGE",
      "portMappings": [
        {
          "containerPort": 8080,
          "hostPort": 0,
          "name": "vip0",
          "labels": {
            "VIP_0": "10.20.0.100:8080"
          }
        }
      ],
      "forcePullImage": true
    }
  },
  "labels": {
    "DCOS_SERVICE_NAME": "vamp",
    "DCOS_SERVICE_SCHEME": "http",
    "DCOS_SERVICE_PORT_INDEX": "0"
  },
  "healthChecks": [
    {
      "protocol": "TCP",
      "gracePeriodSeconds": 30,
      "intervalSeconds": 10,
      "timeoutSeconds": 5,
      "portIndex": 0,
      "maxConsecutiveFailures": 0
    }
  ],
  "env": {
    "VAMP_GATEWAY_DRIVER_LOGSTASH_HOST": "elasticsearch.marathon.mesos",
    "VAMP_PERSISTENCE_DATABASE_ELASTICSEARCH_URL": "http://elasticsearch.marathon.mesos:9200",
    "VAMP_PULSE_ELASTICSEARCH_URL": "http://elasticsearch.marathon.mesos:9200",
    "VAMP_WAIT_FOR": "http://elasticsearch.marathon.mesos:9200/.kibana",
    "VAMP_WORKFLOW_DRIVER_VAMP_URL": "http://10.20.0.100:8080",
    "VAMP_HTTP_API_PORT": "8080"
  }
}

```

Expected: The workflow `VAMP_URL` should match the `VAMP_WORKFLOW_DRIVER_VAMP_URL` value from the Vamp configuration.
